### ISSUE TITLE
Extreme FPS Lags when fighting against Wither

### ISSUE THREAD

**Issue by TheRealPicasso** [Superkat32/Explosive-Enhancement#11] opened 2023-07-14 00:13 UTC
My frames dropped down to 9 Fps while this mod was on when i fighted the wither (Playing in 1.20.1) . I would recommend a settings button for wither explosions to turn it off or edit, or work on the performance with many explosions. Overall a great mod, i like it! I wish there would be more like this to enhance visuals :)

**Comment by Superkat32** [comment] 2023-07-14 03:36
Do a lot of particles being rendered normally cause lag on your device? I'm aware of the obstructed view while fighting the wither(being worked on), however, I haven't heard of the wither causing lag. I have actually tried to detect what has caused the explosion, but was unsuccessful(meaning I wouldn't be able to add a config option to disable the animation for _just_ wither explosions).

In the meantime, there is a config option to disable the mod completely in the "Extras" category. You can disable the mod just before fighting the wither, then re-enable it afterwards.

**Comment by TheRealPicasso** [comment] 2023-07-14 09:25
I just found out that the frame drops do not apply in a singleplayer world. I was on my survival server when I fighted the wither. I will update you when i do it next time on a server, if it still happens.

**Comment by Superkat32** [comment] 2023-07-14 16:01
Alright, thanks for the update.
What other mods are you using? I wonder if maybe something else is causing the lag.

**Comment by TheRealPicasso** [comment] 2023-07-26 21:14
> Alright, thanks for the update.
> What other mods are you using? I wonder if maybe something else is causing the lag.

I will send you my list when I'm back at home on 07.08👍

**Comment by IceBlossom** [comment] 2023-08-10 20:19
Okay, I figured out something. All of this is related to Physics Mod. Here's a couple of videos with a small mod set (Sodium, FRAPI, YACL, EE and Physics Mod):

https://github.com/Superkat32/Explosive-Enhancement/assets/78196119/dcdd45eb-c8cf-4a37-9d22-a7f2552ac58e


https://github.com/Superkat32/Explosive-Enhancement/assets/78196119/56a69c41-a657-4fb3-a96c-859ba489d845


https://github.com/Superkat32/Explosive-Enhancement/assets/78196119/ced7966e-c8d3-4e70-84f5-9b314fd5dc2c

This shows that this is a Physics Mod issue, and not one with EE. I'll send in an issue on the GitHub page for PM, and this issue page should be able to be closed.

**Comment by Superkat32** [comment] 2023-08-10 20:34
The Physics mod could do it, especially if you have a lot of particles spawning from it. But, if the Physics mod isn't installed, then there is still a problem that needs to be fixed.

**Comment by IceBlossom** [comment] 2023-08-10 22:05
No problem! However, since I had no issues with performance with only EE installed, and we don't know the mod list of the person who started this issue, then we just have to wait and see their mod list to check if they have Physics Mod installed.

**Comment by IceBlossom** [comment] 2023-08-11 10:48
Little update! I created an issue page on the Physics Mod GitHub, and now a whole new version is the game released just to fix that one bug! So, if OP does in fact use Physics Mod, they should be able to install the new version and run no problem.

**Comment by Superkat32** [comment] 2023-08-11 14:50
> Little update! I created an issue page on the Physics Mod GitHub, and now a whole new version is the game released just to fix that one bug! So, if OP does in fact use Physics Mod, they should be able to install the new version and run no problem.

The Physics mod developer actually fixed the performance? I figured it would have already been heavily optimized but I guess he had some extra optimization he could do. Impressive!

**Comment by TheRealPicasso** [comment] 2023-08-13 18:44
> Little update! I created an issue page on the Physics Mod GitHub, and now a whole new version is the game released just to fix that one bug! So, if OP does in fact use Physics Mod, they should be able to install the new version and run no problem.

HEY i got no notification here so, yea you guys are right, i do have physics mod installed, i will test it, if the bug is fixed now!

**Comment by Superkat32** [comment] 2023-08-16 22:43
Any updates on the testing?

**Comment by Superkat32** [comment] 2023-09-02 17:00
I am going to close this as everything seems to indicate that the Physics Mod was the cause of this. If you believe this is wrong, please let me know.

Also, if you continue to experience lag issues that you believe was caused by Explosive Enhancement, then please let me know as well.

Have a good day!

**Closed by Superkat32** 2023-09-02 17:00 UTC
Labels: bug
